# Config database v√† jpa
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/money_management
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: 9f25fe001@smtp-brevo.com
    password: ${VERIFY_EMAIL_API_KEY}
    properties:
      mail:
        smtp:
          from: "l.x.k8042@gmail.com"
          auth: true
          starttls:
            enable: true
    protocol: smtp

server:
  servlet:
    context-path: /api/v1.0

money-management:
  frontend:
    url: "http://localhost:5173"